import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const gamesPath = path.join(__dirname, '../data/games.json');
const categoriesPath = path.join(__dirname, '../data/categories.json');

const existing = JSON.parse(readFileSync(gamesPath, 'utf8'));
const existingSlugs = new Set(existing.map(g => g.slug));

// Also block user-specified slugs not to duplicate
const blocked = new Set([
  'smash-karts','territorial-io','skribbl-io','gartic-phone',
  'helix-jump','stack-ball','knife-hit','color-road','dead-zed',
  'masked-forces','football-legends','aquapark-io','madalin-stunt-cars-2',
  'geoguessr', // already g050
]);

function cg(slug) { return `https://www.crazygames.com/embed/${slug}`; }
function thumb(bg, fg, text) { return `https://placehold.co/270x180/${bg}/${fg}?text=${encodeURIComponent(text)}&font=raleway`; }
function banner(bg, fg, text) { return `https://placehold.co/800x450/${bg}/${fg}?text=${encodeURIComponent(text)}&font=raleway`; }

const COLORS = {
  action:      ['1a0a0a','f87171'],
  puzzle:      ['1a0a40','a78bfa'],
  racing:      ['1a1a0a','fbbf24'],
  shooting:    ['0a1a1a','22d3ee'],
  sports:      ['0a0a1a','818cf8'],
  'io-games':  ['0a1a0a','4ade80'],
  hypercasual: ['1a0a1a','e879f9'],
  '2-player':  ['1a1a0a','fde68a'],
};

function g(id, title, slug, category, embedUrl, plays, rating, ratingCount, opts = {}) {
  const [bg, fg] = COLORS[category] || ['1a1a1a','ffffff'];
  return {
    id, title, slug,
    description: opts.desc || `Play ${title} online for free in your browser. No download needed.`,
    shortDescription: opts.short || `Play ${title} free in your browser.`,
    category,
    tags: opts.tags || [],
    thumbnailUrl: opts.thumb || thumb(bg, fg, title),
    bannerUrl: opts.banner || banner(bg, fg, title),
    embedUrl,
    embedType: 'iframe',
    width: opts.w || 960,
    height: opts.h || 540,
    developer: opts.dev || 'CrazyGames',
    plays, rating, ratingCount,
    featured: opts.featured || false,
    isNew: opts.isNew || false,
    isHot: opts.isHot || false,
    addedAt: opts.addedAt || '2024-01-01',
    instructions: opts.instr || 'Follow on-screen instructions.',
    controls: opts.ctrl || { keyboard: 'WASD or Arrow Keys', mouse: 'Click to interact' },
  };
}

const newGames = [
  // ── BATCH 1: Most Searched (g051-g060) ──────────────────────────────────
  g('g051','Subway Surfers','subway-surfers','hypercasual',cg('subway-surfers'),55000000,4.7,220000,{
    dev:'Kiloo Games',featured:true,isHot:true,
    short:'Run, dodge and surf through subway tracks.',
    desc:'The world\'s most downloaded mobile game now in your browser. Run through subway tracks, dodge trains, collect coins, and use hoverboards to escape the inspector.',
    tags:['runner','endless','surfing','subway','mobile-style'],
    instr:'Swipe or use arrow keys to dodge trains. Collect coins to unlock characters.',
    ctrl:{keyboard:'Left/Right arrows to switch lanes, Up to jump, Down to roll',touch:'Swipe in any direction'},
    w:480,h:640,
  }),
  g('g052','Temple Run 2','temple-run-2','hypercasual',cg('temple-run-2'),42000000,4.6,175000,{
    dev:'Imangi Studios',featured:true,isHot:true,
    short:'Run from a demon monkey through ancient temples.',
    desc:'Outrun a demonic monster through stunning jungle and temple environments. Swipe to turn, jump and slide under obstacles, and collect coins as you build an unstoppable run.',
    tags:['runner','endless','temple','mobile-style','obstacles'],
    instr:'Swipe left/right to turn, up to jump, down to slide.',
    ctrl:{keyboard:'Arrow keys to turn/jump/slide'},
    w:480,h:640,
  }),
  g('g053','Minecraft Classic','minecraft-classic','action','https://classic.minecraft.net',80000000,4.9,380000,{
    dev:'Mojang',featured:true,isHot:true,
    short:'The original Minecraft — build anything in your browser.',
    desc:'The original Minecraft Classic is free and runs directly in your browser. Place and break blocks to build anything you can imagine. The game that started a generation of builders.',
    tags:['minecraft','building','sandbox','blocks','classic'],
    instr:'Left-click to break blocks, right-click to place. Use number keys to switch block types.',
    ctrl:{keyboard:'WASD to move, Space to jump, 1-9 to select blocks',mouse:'Left-click break, right-click place'},
    w:960,h:540,
  }),
  g('g054','Among Us Online','among-us-online','io-games',cg('among-us-online-edition'),48000000,4.7,195000,{
    dev:'Innersloth (fan port)',featured:true,isHot:true,
    short:'Find the imposter before they eliminate the crew.',
    desc:'The viral social deduction game in your browser. Complete tasks as a crewmate or sabotage as the imposter. Call meetings and vote out suspects before it\'s too late.',
    tags:['among-us','multiplayer','deception','social','imposter'],
    instr:'Complete tasks around the map. Call meetings if you spot suspicious behavior. Vote out the imposter.',
    ctrl:{keyboard:'WASD to move, E to interact, Q to sabotage (imposter)',mouse:'Click to interact with tasks'},
  }),
  g('g055','Friday Night Funkin','friday-night-funkin','action',cg('friday-night-funkin'),35000000,4.8,145000,{
    dev:'ninjamuffin99',featured:true,isHot:true,
    short:'Rhythm battle game — hit the arrows to the beat.',
    desc:'The viral rhythm game where Boyfriend must out-rap everyone to date his Girlfriend. Hit arrow keys in time with the music across multiple weeks of increasingly hard songs.',
    tags:['rhythm','music','fnf','dancing','arrows'],
    instr:'Press arrow keys in time with the scrolling arrows. Don\'t miss too many or you lose.',
    ctrl:{keyboard:'Arrow keys or WASD to hit notes in time'},
  }),
  g('g056','Roblox','roblox','action','https://www.roblox.com/games',100000000,4.7,450000,{
    dev:'Roblox Corporation',featured:true,isHot:true,
    short:'Millions of games inside one platform.',
    desc:'Roblox is a platform with millions of user-created games. Play obstacle courses, roleplay games, shooters, simulators and more. Create your own game and share it with the world.',
    tags:['roblox','multiplayer','sandbox','games','social'],
    instr:'Create a free account and explore millions of games created by other players.',
    ctrl:{keyboard:'WASD to move, Space to jump, varies by game'},
  }),
  g('g057','Eggy Car','eggy-car','hypercasual',cg('eggy-car'),18000000,4.5,72000,{
    isHot:true,addedAt:'2024-01-10',
    short:'Drive carefully and don\'t drop the egg.',
    desc:'Balance an egg on top of your car as you drive over hilly terrain. Accelerate slowly, brake gently, and whatever you do — don\'t drop the egg.',
    tags:['car','egg','balance','physics','casual'],
    instr:'Use arrow keys to drive. Keep the egg balanced on your car roof.',
    ctrl:{keyboard:'Right arrow to accelerate, Left arrow to brake/reverse'},
  }),
  g('g058','OvO','ovo','action',cg('ovo'),12000000,4.6,48000,{
    isHot:true,addedAt:'2024-01-15',
    short:'Speed through platformer levels with slick parkour.',
    desc:'OvO is a fast-paced platformer where you use momentum-based parkour to blast through levels. Slide, jump, dive and wall-jump through increasingly complex obstacle courses.',
    tags:['platformer','stickman','parkour','speed','skill'],
    instr:'Run and jump through each level. Use speed and momentum for advanced moves.',
    ctrl:{keyboard:'Arrow keys or WASD — down while running to slide, double-tap to dash'},
  }),
  // g059: replacing smash-karts duplicate
  g('g059','Powerline.io','powerline-io','io-games','https://powerline.io',8000000,4.4,32000,{
    isHot:true,addedAt:'2024-01-20',
    short:'Snake meets Tron in this neon multiplayer game.',
    desc:'Guide your neon snake through a grid of other players. Leave a glowing trail and force enemies into your line while surviving as long as possible.',
    tags:['io','snake','neon','multiplayer','tron'],
    instr:'Steer your line to trap other players. Don\'t cross any trail including your own.',
    ctrl:{keyboard:'Arrow keys or WASD to steer',mouse:'Move mouse to steer'},
  }),
  g('g060','Dinosaur Game','dinosaur-game','hypercasual','https://dinosaur-game.io',45000000,4.6,170000,{
    isHot:true,
    short:'The Chrome dino with high score tracking.',
    desc:'Another version of the beloved Chrome dinosaur game with day/night cycle and high score tracking. Jump over cacti, duck under pterodactyls, survive as long as possible.',
    tags:['dino','runner','endless','jumping','chrome'],
    instr:'Press Space to start and jump. Down arrow to duck.',
    ctrl:{keyboard:'Space to jump, Down arrow to duck',touch:'Tap to jump'},
    w:960,h:400,
  }),

  // ── BATCH 2: Top IO Games (g061-g068) ───────────────────────────────────
  g('g061','Zombs Royale','zombs-royale','io-games','https://zombsroyale.io',16000000,4.5,64000,{
    isHot:true,addedAt:'2024-01-05',
    short:'Top-down battle royale .io game.',
    desc:'A top-down 2D battle royale with 100 players. Drop into the map, loot weapons and shields, and be the last player standing. The zone shrinks forcing everyone into conflict.',
    tags:['battle-royale','io','shooting','multiplayer','top-down'],
    instr:'Loot buildings for weapons. Stay inside the safe zone. Eliminate enemies.',
    ctrl:{keyboard:'WASD to move, 1-4 for weapons',mouse:'Aim and left-click to shoot'},
  }),
  g('g062','Surviv.io','surviv-io','io-games','https://surviv.io',13000000,4.4,52000,{
    isHot:true,addedAt:'2024-01-08',
    short:'2D battle royale survival shooter.',
    desc:'A 2D top-down battle royale where you fight to be the last survivor. Loot buildings, find better weapons, and stay inside the red zone. The last player alive wins.',
    tags:['battle-royale','io','shooting','2d','survival'],
    instr:'Find weapons in buildings. Kill others and stay inside the white circle.',
    ctrl:{keyboard:'WASD to move, R reload, F interact',mouse:'Aim and shoot'},
  }),
  g('g063','Lordz.io','lordz-io','io-games','https://www.lordz.io',6000000,4.3,24000,{
    addedAt:'2024-02-01',
    short:'Build an army and conquer other lords.',
    desc:'Collect gold, build an army of knights, archers and dragons, and conquer enemy lords. A real-time strategy .io game that rewards smart expansion and aggressive play.',
    tags:['strategy','io','multiplayer','medieval','rts'],
    instr:'Collect gold to build troops. Attack other players to steal their gold.',
    ctrl:{mouse:'Move to steer your lord, click to build',keyboard:'1-4 to select troop types'},
  }),
  g('g064','Brutal.io','brutal-io','io-games','https://brutal.io',5000000,4.2,20000,{
    addedAt:'2024-02-05',
    short:'Swing a deadly flail and smash other players.',
    desc:'Swing a spiked flail around your vehicle and smash other players. Absorb energy from kills to grow your flail larger. Fast, violent, and deeply satisfying multiplayer chaos.',
    tags:['io','multiplayer','flail','action','competitive'],
    instr:'Drive around swinging your flail. Absorb blue energy to grow.',
    ctrl:{mouse:'Move to drive, flail follows automatically'},
  }),
  g('g065','Hexanaut.io','hexanaut-io','io-games','https://hexanaut.io',4000000,4.3,16000,{
    isNew:true,addedAt:'2024-03-01',
    short:'Claim hexagon territory and dominate the map.',
    desc:'Capture hexagonal territory by surrounding it with your color. Cut off other players\' trails to eliminate them. A beautifully strategic take on the territory .io formula.',
    tags:['io','territory','hexagon','strategy','multiplayer'],
    instr:'Move to capture hexagons. Surround areas to claim them. Cut other players off to eliminate them.',
    ctrl:{mouse:'Move cursor to steer your character'},
  }),
  // g066: replacing territorial-io duplicate
  g('g066','Mope.io','mope-io','io-games','https://mope.io',9000000,4.4,36000,{
    isHot:true,addedAt:'2024-01-12',
    short:'Evolve from mouse to dragon by eating and surviving.',
    desc:'Start as a tiny mouse and eat food and water to evolve up the food chain. Avoid larger animals and hunt smaller ones. Reach the top of the chain to become a mighty dragon.',
    tags:['io','evolution','animals','multiplayer','survival'],
    instr:'Eat food and water to level up. Avoid animals bigger than you. Hunt animals smaller than you.',
    ctrl:{mouse:'Move mouse to steer your animal'},
  }),
  // g067: replacing skribbl-io duplicate
  g('g067','Taming.io','taming-io','io-games','https://taming.io',5500000,4.4,22000,{
    isHot:true,addedAt:'2024-02-10',
    short:'Tame monsters and dominate the arena.',
    desc:'Collect resources, craft weapons, and tame powerful monsters to fight alongside you. Build a base, form alliances, and battle other players in this deep .io survival game.',
    tags:['io','taming','survival','crafting','multiplayer'],
    instr:'Gather resources, craft gear, and tame monsters. Protect your windmill from enemies.',
    ctrl:{keyboard:'WASD to move, E to interact',mouse:'Aim and click to attack'},
  }),
  // g068: replacing gartic-phone duplicate
  g('g068','Kirka.io','kirka-io','shooting','https://kirka.io',7000000,4.5,28000,{
    isHot:true,addedAt:'2024-02-15',
    short:'Fast-paced browser FPS with clans and ranks.',
    desc:'A polished browser-based first-person shooter with multiple maps and modes. Join a clan, rank up, and compete in fast-paced team deathmatches in this highly capable browser FPS.',
    tags:['fps','io','multiplayer','shooting','3d'],
    instr:'Join a match and eliminate enemies. Work with your team to win rounds.',
    ctrl:{keyboard:'WASD to move, R reload, Space jump',mouse:'Aim and left-click to shoot'},
  }),

  // ── BATCH 3: Puzzle & Brain Games (g069-g074) ───────────────────────────
  g('g069','Connections','connections','puzzle','https://www.nytimes.com/games/connections',25000000,4.8,98000,{
    dev:'New York Times',featured:true,isHot:true,
    short:'Group 16 words into 4 hidden categories.',
    desc:'The New York Times daily word puzzle. Find the four groups of four words that share a hidden connection. Sounds simple — finding the tricky connections will surprise you.',
    tags:['nyt','daily','grouping','words','brain'],
    instr:'Select 4 words you think belong together. Submit to see if you found a valid group. You have 4 mistakes allowed.',
    ctrl:{mouse:'Click words to select them, submit to guess the group'},
    w:800,h:600,
  }),
  g('g070','Nerdle','nerdle','puzzle','https://nerdlegame.com',8000000,4.6,32000,{
    addedAt:'2024-02-10',
    short:'Wordle but with math equations.',
    desc:'Guess the hidden math equation in 6 tries. Like Wordle but with numbers and operators. Color clues tell you which parts of the equation are correct, present or absent.',
    tags:['math','numbers','daily','wordle-like','equations'],
    instr:'Enter a valid math equation as your guess. Colors reveal correct positions.',
    ctrl:{keyboard:'Type numbers and operators',mouse:'Click the on-screen keypad'},
    w:800,h:600,
  }),
  g('g071','Globle','globle','puzzle','https://globle-game.com',6000000,4.5,24000,{
    addedAt:'2024-02-15',
    short:'Guess the mystery country using globe heat clues.',
    desc:'Guess the secret country of the day. Each guess colors the globe — the warmer the color, the closer you are. A beautiful geography game that teaches as you play.',
    tags:['geography','globe','daily','countries','guessing'],
    instr:'Type a country name to guess. The globe heats up near the mystery country.',
    ctrl:{keyboard:'Type country names to guess',mouse:'Rotate the globe'},
    w:800,h:600,
  }),
  g('g072','Worldle','worldle','puzzle','https://worldle.teuteuf.fr',7000000,4.6,28000,{
    addedAt:'2024-02-20',
    short:'Guess the country from its silhouette shape.',
    desc:'Identify a country from its outline shape in 6 guesses. After each guess you get the distance and direction to the mystery country. Tests your geography knowledge.',
    tags:['geography','countries','daily','shapes','guessing'],
    instr:'Look at the country silhouette and guess its name. Each guess tells you distance and direction.',
    ctrl:{keyboard:'Type country names to guess'},
    w:800,h:600,
  }),
  g('g073','Jigsaw Puzzles','jigsaw-puzzles','puzzle',cg('jigsaw-puzzles-online'),9000000,4.5,36000,{
    addedAt:'2024-02-01',
    short:'Relaxing jigsaw puzzles with beautiful images.',
    desc:'Hundreds of beautiful jigsaw puzzles with adjustable difficulty. Choose from landscapes, animals, architecture and more. Drag and place pieces to complete each image.',
    tags:['jigsaw','relaxing','pictures','assembling','casual'],
    instr:'Drag pieces from the side panel and place them on the board.',
    ctrl:{mouse:'Click and drag pieces to place them'},
  }),
  g('g074','Mahjong Classic','mahjong-classic','puzzle',cg('mahjong-classic'),11000000,4.6,44000,{
    addedAt:'2024-01-20',
    short:'Classic tile-matching mahjong solitaire.',
    desc:'The classic Chinese tile-matching game. Match identical free tiles to remove them from the board. Clear the entire board to win. Multiple layouts and difficulty levels.',
    tags:['mahjong','tiles','matching','classic','brain'],
    instr:'Click two matching free tiles to remove them. A tile is free if nothing is on top and one side is open.',
    ctrl:{mouse:'Click tiles to select and match them'},
  }),

  // ── BATCH 4: Action & More (g075-g090) ──────────────────────────────────
  g('g075','Vex 6','vex-6','action',cg('vex-6'),4200000,4.5,17000,{
    dev:'Amazing Adam',isHot:true,isNew:true,addedAt:'2024-03-15',
    short:'The latest brutal stickman platformer.',
    desc:'Vex 6 continues the punishing stickman platformer series with brand new acts, fresh obstacles and devious traps. A must-play for fans of precision platformers.',
    tags:['platformer','stickman','hard','parkour','skill'],
    instr:'Navigate each act avoiding all hazards. Reach the exit flag alive.',
    ctrl:{keyboard:'WASD or Arrow Keys to move and jump'},
  }),
  g('g076','Kogama','kogama','action',cg('kogama-free-run'),6000000,4.3,24000,{
    addedAt:'2024-02-10',
    short:'3D multiplayer building and parkour world.',
    desc:'Build your own 3D worlds and play in worlds others have created. Run, jump, fight and explore in this colorful multiplayer block-building platformer.',
    tags:['3d','building','multiplayer','parkour','sandbox'],
    instr:'Join a world or create your own. Collect gold stars and reach checkpoints.',
    ctrl:{keyboard:'WASD to move, Space to jump',mouse:'Look around'},
  }),
  g('g077','Bloons Tower Defense 5','bloons-tower-defense-5','action',cg('bloons-tower-defense-5'),13000000,4.8,52000,{
    dev:'Ninja Kiwi',featured:true,isHot:true,addedAt:'2024-01-05',
    short:'Pop bloons with monkey towers before they escape.',
    desc:'The legendary tower defense game. Place monkey towers to pop waves of bloons before they reach the exit. Hundreds of levels, towers, and upgrade combinations.',
    tags:['tower-defense','strategy','balloons','monkeys','waves'],
    instr:'Place monkey towers along the bloon path. Upgrade towers to handle tougher bloons.',
    ctrl:{mouse:'Click to place and upgrade towers'},
  }),
  g('g078','Strike Force Heroes','strike-force-heroes','action',cg('strike-force-heroes'),5000000,4.4,20000,{
    dev:'Sky9 Games',addedAt:'2024-02-05',
    short:'Side-scrolling shooter with RPG progression.',
    desc:'Build a squad of elite soldiers and battle through campaigns. Level up heroes, unlock new classes and weapons, and dominate in multiplayer challenges.',
    tags:['shooter','sidescroller','rpg','soldiers','action'],
    instr:'Eliminate enemies to earn XP. Level up your heroes and unlock stronger abilities.',
    ctrl:{keyboard:'WASD to move, mouse to aim and shoot, Q/E for abilities'},
  }),
  g('g079','Earn to Die 2','earn-to-die-2','action',cg('earn-to-die-2'),7000000,4.5,28000,{
    dev:'Not Doppler',isHot:true,addedAt:'2024-01-25',
    short:'Drive through zombie hordes and upgrade your car.',
    desc:'Drive your car through zombie-infested wastelands to reach the evacuation point. Earn cash by smashing zombies and upgrade your vehicle with bigger engines and guns.',
    tags:['zombies','driving','upgrades','survival','car'],
    instr:'Drive as far as possible each run. Use earned cash to upgrade your vehicle.',
    ctrl:{keyboard:'Up arrow to accelerate, Down to brake, Left/Right to tilt'},
  }),
  g('g080','Jacksmith','jacksmith','action',cg('jacksmith'),4000000,4.6,16000,{
    dev:'Flipline Studios',addedAt:'2024-02-20',
    short:'Forge weapons for warrior customers.',
    desc:'Play as a donkey blacksmith crafting weapons for an army of warriors. Pour molten metal into molds, hammer it into shape, and send your warriors into battle.',
    tags:['crafting','smith','donkey','weapons','strategy'],
    instr:'Follow crafting steps precisely to make the best weapons.',
    ctrl:{mouse:'Click and drag through all crafting stages'},
  }),
  g('g081','Super Smash Flash 2','super-smash-flash-2','action',cg('super-smash-flash-2'),18000000,4.7,72000,{
    dev:'McLeodGaming',featured:true,isHot:true,addedAt:'2024-01-10',
    short:'Browser Smash Bros with iconic characters.',
    desc:'The legendary fan-made Smash Bros game in your browser. Play as Mario, Sonic, Naruto, Goku and dozens more. Battle locally or against AI across many classic stages.',
    tags:['fighting','smash','multiplayer','characters','2player'],
    instr:'Knock opponents off the stage to score. Higher damage = farther they fly.',
    ctrl:{keyboard:'Player 1: WASD move, J attack, K special, L shield'},
  }),
  g('g082','Mutilate a Doll 2','mutilate-a-doll-2','action',cg('mutilate-a-doll-2'),8000000,4.5,32000,{
    addedAt:'2024-02-08',
    short:'Physics sandbox — ragdoll destruction toy.',
    desc:'A physics sandbox where you spawn weapons, tools, and objects to interact with a ragdoll. Completely open-ended — no objectives, just creative destruction.',
    tags:['sandbox','ragdoll','physics','destruction','toys'],
    instr:'Spawn items from the menu and use them on the ragdoll.',
    ctrl:{mouse:'Spawn and throw objects, interact with ragdoll'},
  }),
  g('g083','Bouncy Rush','bouncy-rush','hypercasual',cg('bouncy-rush'),5000000,4.2,20000,{
    isNew:true,addedAt:'2024-03-10',
    short:'Bounce your way through obstacles.',
    desc:'Guide your bouncy ball through an obstacle-filled course. Timing each bounce perfectly is the key to survival in this simple yet addictive hypercasual runner.',
    tags:['bouncing','casual','ball','rush','mobile-style'],
    instr:'Tap or click to bounce. Time your bounces to avoid obstacles.',
    ctrl:{mouse:'Click to bounce',touch:'Tap to bounce'},
    w:480,h:640,
  }),
  g('g084','Basketball FRVR','basketball-frvr','sports',cg('basketball-frvr'),9000000,4.4,36000,{
    dev:'FRVR',isHot:true,addedAt:'2024-01-20',
    short:'Shoot hoops with satisfying arc physics.',
    desc:'Clean, satisfying basketball shooting game. Aim and shoot to score baskets. The basket moves as you progress, testing your arc and timing. Endlessly replayable.',
    tags:['basketball','shooting','hoops','casual','aim'],
    instr:'Click and drag to aim your shot. Release to shoot. Nail the arc to score.',
    ctrl:{mouse:'Click drag and release to shoot'},
    w:480,h:640,
  }),
  g('g085','Archery World Tour','archery-world-tour','sports',cg('archery-world-tour'),4000000,4.3,16000,{
    dev:'Inlogic Software',addedAt:'2024-02-15',
    short:'Shoot bullseyes across global archery ranges.',
    desc:'Travel the world competing in archery tournaments. Account for wind, distance, and elevation as you aim for bullseyes across stunning international locations.',
    tags:['archery','bow','aim','precision','tour'],
    instr:'Aim with the moving target and click when lined up for the bullseye.',
    ctrl:{mouse:'Move to aim, click to release arrow'},
  }),
  g('g086','Pool Club','pool-club','sports',cg('pool-club'),8000000,4.5,32000,{
    dev:'Miniclip',isHot:true,addedAt:'2024-01-15',
    short:'Realistic 8-ball pool against online opponents.',
    desc:'Play 8-ball pool against players around the world. Realistic physics, multiple tables, and a progression system. Pot all your balls then sink the 8-ball to win.',
    tags:['pool','billiards','cue','8ball','multiplayer'],
    instr:'Aim the cue, set power, and shoot. Pot all your balls then sink the 8-ball.',
    ctrl:{mouse:'Aim cue, click and drag for power'},
  }),
  g('g087','Boxing Random','boxing-random','2-player',cg('boxing-random'),5000000,4.4,20000,{
    dev:'RHM Interactive',isHot:true,addedAt:'2024-02-01',
    short:'Wacky 2-player boxing with random rules.',
    desc:'Two players face off in wacky boxing matches where the rules change every round. Ragdoll physics make every punch hilarious. First to 5 knockdowns wins.',
    tags:['boxing','random','2player','funny','physics'],
    instr:'Hit your opponent to knock them over. Different random rules apply each round.',
    ctrl:{keyboard:'Player 1: W to punch | Player 2: Up arrow to punch'},
  }),
  g('g088','Snow Rider 3D','snow-rider-3d','racing',cg('snow-rider-3d'),7000000,4.5,28000,{
    isHot:true,addedAt:'2024-01-10',
    short:'Sled down an endless snowy mountain.',
    desc:'Race down an infinite snowy mountain on a sled. Dodge trees, rocks and snowmen while collecting gifts. Beautiful 3D winter visuals make this endlessly calming and fun.',
    tags:['snow','sled','3d','endless','winter'],
    instr:'Steer left and right to avoid obstacles. Collect presents for bonus points.',
    ctrl:{keyboard:'Left/Right arrows to steer',touch:'Tilt to steer'},
  }),
  g('g089','Rocket Soccer Derby','rocket-soccer-derby','sports',cg('rocket-soccer-derby'),4000000,4.3,16000,{
    isNew:true,addedAt:'2024-03-05',
    short:'Rocket-powered cars playing soccer.',
    desc:'Drive rocket-powered cars and hit a giant ball into the enemy goal. Inspired by Rocket League, this browser version captures the same chaotic joy. Boost, jump and score.',
    tags:['rocket','soccer','cars','derby','multiplayer'],
    instr:'Drive into the ball to hit it towards the enemy goal. Collect boost to go faster.',
    ctrl:{keyboard:'WASD to drive, Space for boost'},
  }),
  g('g090','Basketball Legends','basketball-legends','sports',cg('basketball-legends'),6000000,4.5,24000,{
    dev:'MadPuffers',isHot:true,addedAt:'2024-01-18',
    short:'1v1 basketball with legendary players.',
    desc:'Play 1v1 or 2v2 basketball with legendary players. Dribble past defenders, pull off trick shots, and dunk on your opponent. Multiple play modes and unlockable characters.',
    tags:['basketball','legends','1v1','sports','multiplayer'],
    instr:'Dribble past your opponent and shoot to score. Use special moves to gain an advantage.',
    ctrl:{keyboard:'WASD to move, B to shoot/steal, V to super shot'},
  }),

  // ── BATCH 5: Classic & Casual (g091-g110) ───────────────────────────────
  g('g091','Solitaire Classic','solitaire-classic','puzzle',cg('solitaire-classic'),14000000,4.7,56000,{
    dev:'Arkadium',addedAt:'2024-01-01',
    short:'Classic Klondike solitaire in your browser.',
    desc:'The iconic Klondike solitaire game, clean and free in your browser. Build four foundation piles by suit from Ace to King. Satisfying, relaxing, and endlessly replayable.',
    tags:['cards','solitaire','classic','relaxing','klondike'],
    instr:'Move cards to build sequences in alternating colors. Build foundations from Ace to King.',
    ctrl:{mouse:'Click or drag cards to move them'},
  }),
  g('g092','Spider Solitaire','spider-solitaire','puzzle',cg('spider-solitaire'),9000000,4.6,36000,{
    dev:'Arkadium',addedAt:'2024-01-05',
    short:'The challenging 2-deck solitaire variant.',
    desc:'Spider Solitaire uses two decks and is one of the most challenging solitaire variants. Build complete sequences from King to Ace in the same suit to clear the tableau.',
    tags:['cards','solitaire','spider','challenging','classic'],
    instr:'Build sequences from King to Ace in the same suit. Complete all 8 sequences to win.',
    ctrl:{mouse:'Click or drag cards to move them'},
  }),
  g('g093','FreeCell','freecell','puzzle',cg('freecell'),7000000,4.5,28000,{
    dev:'Arkadium',addedAt:'2024-01-08',
    short:'Strategic solitaire with four free cells.',
    desc:'Unlike Klondike, almost every FreeCell deal is solvable with the right strategy. Use the four free cells as temporary storage to build all cards up to the foundations.',
    tags:['cards','solitaire','freecell','strategy','classic'],
    instr:'Use the four free cells to temporarily hold cards. Build foundations from Ace to King by suit.',
    ctrl:{mouse:'Click or drag cards to move them'},
  }),
  g('g094','Bubble Shooter','bubble-shooter','puzzle',cg('bubble-shooter'),15000000,4.5,60000,{
    isHot:true,addedAt:'2024-01-10',
    short:'Match and pop colorful bubbles.',
    desc:'Aim and shoot bubbles to match groups of three or more of the same color. Pop all the bubbles before they reach the bottom. Hundreds of increasingly challenging levels.',
    tags:['bubbles','shooting','matching','casual','colorful'],
    instr:'Aim your bubble shooter and fire. Match 3 or more bubbles of the same color to pop them.',
    ctrl:{mouse:'Move to aim, click to shoot'},
  }),
  g('g095','Zuma Deluxe','zuma-deluxe','puzzle',cg('zuma-deluxe'),8000000,4.5,32000,{
    isHot:true,addedAt:'2024-01-12',
    short:'Shoot colored balls to destroy the chain.',
    desc:'Fire colored balls from the frog to match groups of 3 or more in the rolling chain. Clear the chain before it reaches the skull. A classic puzzle game with satisfying combos.',
    tags:['zuma','balls','chain','matching','classic'],
    instr:'Aim and shoot balls to match colors in the chain. Match 3+ to destroy them.',
    ctrl:{mouse:'Move to aim, left-click to shoot, right-click to swap ball color'},
  }),
  g('g096','Candy Crush Saga','candy-crush-saga','puzzle','https://king.com/play/candycrush',50000000,4.6,200000,{
    dev:'King',featured:true,isHot:true,
    short:'Match colorful candies in this mega-hit puzzle game.',
    desc:'The legendary match-3 puzzle game with hundreds of levels. Swap and match candies to clear objectives, unlock special candy types, and progress through a sweet world.',
    tags:['candy','match3','puzzle','casual','levels'],
    instr:'Swap adjacent candies to match 3 or more. Clear objectives to complete each level.',
    ctrl:{mouse:'Click and drag candies to swap them'},
  }),
  g('g097','Cut the Rope','cut-the-rope','puzzle',cg('cut-the-rope'),18000000,4.7,72000,{
    dev:'ZeptoLab',isHot:true,addedAt:'2024-01-15',
    short:'Feed Om Nom candy by cutting the ropes.',
    desc:'The beloved physics puzzle game. Cut ropes at the right moment to swing candy into the little monster Om Nom\'s mouth. Hundreds of levels with increasingly clever contraptions.',
    tags:['physics','ropes','cutting','candy','casual'],
    instr:'Cut ropes to swing the candy into Om Nom\'s mouth. Collect stars for bonus points.',
    ctrl:{mouse:'Click and drag to cut ropes'},
  }),
  g('g098',"Papa's Pizzeria","papas-pizzeria",'hypercasual',cg('papas-pizzeria'),9000000,4.7,36000,{
    dev:'Flipline Studios',featured:true,isHot:true,addedAt:'2024-01-20',
    short:"Manage Papa's pizza restaurant in this classic sim.",
    desc:"Take orders, build pizzas and manage your restaurant in the beloved classic from Flipline Studios. Keep customers happy to earn tips and upgrades in this addictive management game.",
    tags:['cooking','papa','management','pizza','simulation'],
    instr:'Take customer orders, build pizzas with the right toppings, and bake them to perfection.',
    ctrl:{mouse:'Click to take orders, drag toppings, manage timers'},
  }),
  g('g099',"Papa's Burgeria","papas-burgeria",'hypercasual',cg('papas-burgeria'),8000000,4.6,32000,{
    dev:'Flipline Studios',featured:true,isHot:true,addedAt:'2024-01-22',
    short:"Run Papa's burger joint — grill, stack, serve.",
    desc:'Work the grill and build perfect burgers for Papa\'s Burgeria customers. Get the patties right, stack ingredients in the correct order, and keep the line moving to earn big tips.',
    tags:['cooking','papa','management','burger','simulation'],
    instr:'Grill patties to order, stack toppings correctly, and serve customers before they get impatient.',
    ctrl:{mouse:'Click to cook, drag and drop ingredients to build burgers'},
  }),
  g('g100',"Papa's Freezeria","papas-freezeria",'hypercasual',cg('papas-freezeria'),7500000,4.6,30000,{
    dev:'Flipline Studios',isHot:true,addedAt:'2024-01-24',
    short:'Blend frozen treats in this cool Papa sim.',
    desc:'Run a beachside ice cream shop. Blend drinks, add mix-ins, and top with syrups and whipped cream. Keep up with the summer rush to earn maximum tips.',
    tags:['cooking','papa','management','icecream','simulation'],
    instr:'Blend ingredients to the right consistency, add toppings in the correct order, and serve happy customers.',
    ctrl:{mouse:'Click to blend, drag toppings to add them'},
  }),
  g('g101','Run 3','run-3','hypercasual',cg('run-3'),22000000,4.7,88000,{
    dev:'Player 03',featured:true,isHot:true,addedAt:'2024-01-01',
    short:'Run through rotating space tunnels endlessly.',
    desc:'Run through an infinite series of rotating space tunnels, jumping over gaps and switching gravity. The tunnels get more complex and the gaps larger as you progress.',
    tags:['running','tunnel','endless','alien','space'],
    instr:'Run forward automatically. Jump over gaps. Rotate the tunnel by running on the walls.',
    ctrl:{keyboard:'Left/Right arrows to steer, Space to jump'},
  }),
  g('g102','Run 2','run-2','hypercasual',cg('run-2'),12000000,4.5,48000,{
    dev:'Player 03',isHot:true,addedAt:'2024-01-03',
    short:'The original space tunnel running game.',
    desc:'The original tunnel running game that spawned a series. Navigate a rotating corridor through outer space, jumping over gaps and switching gravity to keep going.',
    tags:['running','tunnel','endless','space','classic'],
    instr:'Run and jump through the tunnel. Rotate by running on the walls to avoid falling off.',
    ctrl:{keyboard:'Arrow keys to steer, Space to jump'},
  }),
  g('g103','Fancy Pants Adventure','fancy-pants-adventure','action',cg('fancy-pants-adventure'),8000000,4.6,32000,{
    dev:'Brad Borne',isHot:true,addedAt:'2024-01-28',
    short:'Smooth stickman platformer with bouncy movement.',
    desc:'Guide the pants-wearing stickman through beautifully smooth platformer levels. The fluid animation and momentum-based movement feel unlike any other browser platformer.',
    tags:['platformer','fancy','pants','smooth','running'],
    instr:'Run, jump, and roll through levels. Collect squiggles and find the exit.',
    ctrl:{keyboard:'Arrow keys to run and jump, Down to roll'},
  }),
  g('g104','Super Mario 63','super-mario-63','action',cg('super-mario-63'),10000000,4.7,40000,{
    dev:'Runouw',isHot:true,addedAt:'2024-01-30',
    short:'Fan-made Mario 64-style platformer in the browser.',
    desc:'An impressive fan-made Super Mario 64 port for the browser. Run, jump, triple jump, and wall-kick through hub worlds collecting stars. Captures the magic of the N64 classic.',
    tags:['mario','platformer','3d','nintendo','fan-game'],
    instr:'Collect stars by completing level objectives. Each course has multiple stars to find.',
    ctrl:{keyboard:'WASD to move, Space to jump, S to crouch',mouse:'Control camera'},
  }),
  g('g105','N-Game','n-game','action',cg('n-game'),5000000,4.4,20000,{
    dev:'Metanet Software',addedAt:'2024-02-05',
    short:'Minimalist ninja platformer with deadly obstacles.',
    desc:'Navigate a minimalist ninja through levels filled with mines, lasers, and physics traps. The simple art style hides incredibly precise platforming that rewards mastery.',
    tags:['ninja','platformer','minimalist','hard','precision'],
    instr:'Reach the exit of each level. Collect gold along the way. Avoid all hazards.',
    ctrl:{keyboard:'Arrow keys to run, Z to jump'},
  }),
  g('g106','Learn to Fly 3','learn-to-fly-3','action',cg('learn-to-fly-3'),6000000,4.5,24000,{
    dev:'Light Bringer Games',addedAt:'2024-02-08',
    short:'Launch a penguin and upgrade for maximum distance.',
    desc:'Help a determined penguin learn to fly. Launch from a ramp, use boosters and gliders, and upgrade your gear between runs. Keep improving your distance until you reach the moon.',
    tags:['penguin','flying','upgrades','idle','launch'],
    instr:'Launch your penguin and use boosters to go further. Earn cash to buy upgrades.',
    ctrl:{keyboard:'Arrow keys to steer, Space to use boost',mouse:'Click to activate special items'},
  }),
  g('g107','Fireboy and Watergirl 2','fireboy-and-watergirl-2','2-player',cg('fireboy-and-watergirl-2'),11000000,4.7,44000,{
    dev:'Oslo Albet',isHot:true,addedAt:'2024-01-05',
    short:'Co-op puzzle platformer in the light temple.',
    desc:'Fireboy and Watergirl return in the Light Temple. Use light beams and mirrors to solve puzzles and guide both characters to their exits. Play with a friend or control both.',
    tags:['2player','coop','puzzle','platformer','light'],
    instr:'Guide both characters to their exits. Use mirrors to redirect light beams and open doors.',
    ctrl:{keyboard:'Fireboy: Arrow Keys | Watergirl: WAD'},
  }),
  g('g108','Fireboy and Watergirl 3','fireboy-and-watergirl-3','2-player',cg('fireboy-and-watergirl-3'),10000000,4.7,40000,{
    dev:'Oslo Albet',isHot:true,addedAt:'2024-01-07',
    short:'Co-op puzzle platformer in the ice temple.',
    desc:'The dynamic duo ventures into the Ice Temple. New ice mechanics let you slide across frozen surfaces and solve uniquely chilly puzzles. Works great solo or with a partner.',
    tags:['2player','coop','puzzle','platformer','ice'],
    instr:'Navigate icy platforms and solve puzzles. Each character can only touch their matching pools.',
    ctrl:{keyboard:'Fireboy: Arrow Keys | Watergirl: WAD'},
  }),
  g('g109','Stick Fight Online','stick-fight-online','2-player',cg('stick-fight-online'),4500000,4.4,18000,{
    isHot:true,addedAt:'2024-02-10',
    short:'2-player stickman brawler with weapons.',
    desc:'Two stickmen beat each other senseless across chaotic stages. Pick up weapons, use the environment, and knock your opponent out. Fast rounds make for great local multiplayer.',
    tags:['stickman','fighting','2player','weapons','brawler'],
    instr:'Beat your opponent by knocking out their health. Grab weapons for an advantage.',
    ctrl:{keyboard:'Player 1: WASD move + F attack | Player 2: Arrow keys + L attack'},
  }),
  g('g110','Tug the Table','tug-the-table','2-player',cg('tug-the-table'),3500000,4.3,14000,{
    addedAt:'2024-02-15',
    short:'2-player tug of war — pull the table to your side.',
    desc:'Two players compete to pull a table to their side of the screen. Hold your button to grab and pull. The first player to drag the table off screen wins. Simple, tense and hilarious.',
    tags:['2player','tug','funny','physics','competitive'],
    instr:'Hold your key to grab and pull the table. Drag it all the way to your side to win.',
    ctrl:{keyboard:'Player 1: hold E | Player 2: hold I'},
  }),

  // ── BATCH 6: Trending & Newer (g111-g130) ───────────────────────────────
  g('g111','Monkey Mart','monkey-mart','hypercasual',cg('monkey-mart'),8000000,4.7,32000,{
    isHot:true,addedAt:'2024-02-20',
    short:'Run a supermarket as a busy monkey.',
    desc:'Grow produce on your farm, stock your supermarket shelves, and serve customers as a hardworking monkey. An addictive idle management game with charming visuals.',
    tags:['monkey','supermarket','idle','management','casual'],
    instr:'Harvest crops and stock shelves. Serve customers automatically. Use cash to expand your mart.',
    ctrl:{keyboard:'WASD or Arrow keys to move',mouse:'Click to interact'},
  }),
  g('g112','Capybara Clicker','capybara-clicker','hypercasual',cg('capybara-clicker'),6000000,4.5,24000,{
    isHot:true,isNew:true,addedAt:'2024-03-01',
    short:'Click capybaras and build an army of them.',
    desc:'Click the capybara to earn capybaras, then buy upgrades to generate more automatically. The internet\'s favorite animal now starring in its own idle clicker.',
    tags:['capybara','clicker','idle','funny','casual'],
    instr:'Click the capybara to earn capybaras. Buy upgrades to multiply your capybara production.',
    ctrl:{mouse:'Click to earn capybaras, click upgrades to purchase'},
  }),
  g('g113','Banana Clicker','banana-clicker','hypercasual',cg('banana-clicker'),5000000,4.3,20000,{
    isHot:true,isNew:true,addedAt:'2024-03-05',
    short:'The meme clicker — click bananas obsessively.',
    desc:'Click the banana. Buy upgrades. Get more bananas. The most absurdly addictive clicker game of the moment. Simple mechanics hide surprising depth in the upgrade tree.',
    tags:['banana','clicker','idle','meme','casual'],
    instr:'Click the banana to earn bananas. Buy upgrades to automate banana production.',
    ctrl:{mouse:'Click banana to earn, click shop items to buy'},
  }),
  g('g114','Pokedoku','pokedoku','puzzle','https://pokedoku.com',10000000,4.8,40000,{
    dev:'Pokedoku',isHot:true,addedAt:'2024-02-25',
    short:'Pokémon meets Sudoku — fill the 3x3 grid.',
    desc:'A daily Pokémon grid puzzle. Fill each cell with a Pokémon that satisfies both row and column criteria. Each Pokémon can only be used once, and you only get 9 guesses.',
    tags:['pokemon','sudoku','daily','grid','trivia'],
    instr:'Fill each cell with a Pokémon that satisfies both its row and column condition. 9 guesses total.',
    ctrl:{keyboard:'Type Pokémon names to search',mouse:'Click to select cell and confirm guess'},
    w:800,h:600,
  }),
  g('g115','Immaculate Grid','immaculate-grid','puzzle','https://immaculategrid.com',8000000,4.7,32000,{
    dev:'Immaculate Grid',isHot:true,addedAt:'2024-03-01',
    short:'Sports trivia grid — fill 9 squares with players.',
    desc:'A daily sports trivia challenge. Fill a 3x3 grid where each cell requires a player who satisfies both the row and column criteria. Tests the depth of your sports knowledge.',
    tags:['sports','grid','daily','trivia','players'],
    instr:'Name a player who played for both the row team/stat and column team/stat. 9 guesses total.',
    ctrl:{keyboard:'Type player names to search',mouse:'Click cells to select'},
    w:800,h:600,
  }),
  g('g116','Rankdle','rankdle','puzzle','https://rankdle.gg',3500000,4.5,14000,{
    isNew:true,addedAt:'2024-03-10',
    short:'Guess the rank of players in game clips.',
    desc:'Watch short clips of players in popular games and guess what rank they are. Daily challenges test your ability to spot the differences between skill levels. A great daily puzzle for gamers.',
    tags:['gaming','daily','clips','guessing','ranks'],
    instr:'Watch the clip and guess the player\'s rank. Closest guess wins the most points.',
    ctrl:{mouse:'Click to select your rank guess'},
    w:800,h:600,
  }),
  g('g117','Quordle','quordle','puzzle','https://quordlegame.com',12000000,4.7,48000,{
    isHot:true,addedAt:'2024-02-01',
    short:'Guess 4 Wordle words simultaneously.',
    desc:'Solve four Wordle puzzles at the same time using the same guesses. Each guess applies to all four boards. You have 9 attempts to solve all four 5-letter words.',
    tags:['word','daily','letters','wordle-like','hard'],
    instr:'Type a 5-letter word. Your guess reveals color clues on all four boards simultaneously.',
    ctrl:{keyboard:'Type letters and press Enter',mouse:'Click the on-screen keyboard'},
    w:800,h:600,
  }),
  g('g118','Sporcle','sporcle','puzzle','https://sporcle.com',20000000,4.6,80000,{
    dev:'Sporcle Inc',isHot:true,addedAt:'2024-01-01',
    short:'Thousands of trivia quizzes on every topic.',
    desc:'The world\'s largest trivia quiz site. Test your knowledge on geography, pop culture, science, sports, music and more. Play daily quizzes or challenge friends.',
    tags:['trivia','quizzes','geography','lists','brain'],
    instr:'Type your answers before the timer runs out. Each quiz has different rules and objectives.',
    ctrl:{keyboard:'Type answers',mouse:'Click to select or submit'},
    w:800,h:600,
  }),
  g('g119','TypeRacer','typeracer','hypercasual','https://play.typeracer.com',15000000,4.7,60000,{
    dev:'TypeRacer',isHot:true,addedAt:'2024-01-01',
    short:'Race by typing — the faster you type the faster you go.',
    desc:'Compete against players worldwide in real-time typing races. Type the given text as fast and accurately as possible. Track your WPM, improve over time, and climb the leaderboards.',
    tags:['typing','racing','speed','words','competitive'],
    instr:'Wait for the light, then type the text shown as fast and accurately as possible.',
    ctrl:{keyboard:'Type the on-screen text to race'},
    w:800,h:600,
  }),
  g('g120','Nitro Type','nitro-type','hypercasual','https://nitrotype.com',12000000,4.7,48000,{
    dev:'Nitro Type',isHot:true,addedAt:'2024-01-03',
    short:'Typing racing game with real cars and upgrades.',
    desc:'Type your way to victory in multiplayer racing. The faster you type, the faster your car goes. Earn cash to buy new cars and compete against players worldwide.',
    tags:['typing','racing','cars','speed','multiplayer'],
    instr:'Type the displayed text as fast as possible. Your car\'s speed matches your WPM.',
    ctrl:{keyboard:'Type the displayed text accurately'},
    w:960,h:540,
  }),
  g('g121','10 Fast Fingers','ten-fast-fingers','hypercasual','https://10fastfingers.com',10000000,4.6,40000,{
    dev:'10FastFingers',addedAt:'2024-01-05',
    short:'Test your typing speed in 60 seconds.',
    desc:'The popular 1-minute typing speed test. Type as many words as possible in 60 seconds. Compete in multiplayer races or practice with custom texts to improve your WPM.',
    tags:['typing','speed','words','test','wpm'],
    instr:'Type the highlighted word and press Space to advance. Finish as many words as possible in 60 seconds.',
    ctrl:{keyboard:'Type words and press Space to advance'},
    w:800,h:600,
  }),
  g('g122','Kahoot','kahoot','puzzle','https://kahoot.it',40000000,4.8,160000,{
    dev:'Kahoot!',featured:true,isHot:true,addedAt:'2024-01-01',
    short:'Live trivia quiz games — join with a game pin.',
    desc:'The world\'s most popular quiz platform. Join a live game using a code, answer questions against others in real time, and see how you rank on the leaderboard. Used in schools worldwide.',
    tags:['trivia','quiz','multiplayer','education','live'],
    instr:'Enter the game pin to join. Select the correct answer before the timer runs out.',
    ctrl:{mouse:'Click the answer button',touch:'Tap to select answer'},
    w:960,h:540,
  }),
  g('g123','Quizlet Live','quizlet-live','puzzle','https://quizlet.com/live',18000000,4.6,72000,{
    dev:'Quizlet',isHot:true,addedAt:'2024-01-08',
    short:'Team-based study quiz game.',
    desc:'Compete in live team-based quizzes built from Quizlet study sets. Your team must collectively answer questions by choosing the right definition for each term. Great for study groups.',
    tags:['study','flashcards','learning','multiplayer','teams'],
    instr:'Work with your team to match terms to definitions. Only your device shows certain answers.',
    ctrl:{mouse:'Click your answer',touch:'Tap to select'},
    w:960,h:540,
  }),
  g('g124','Scratch Games','scratch-games','action','https://scratch.mit.edu/explore/projects/games',5000000,4.3,20000,{
    dev:'MIT / Scratch Community',addedAt:'2024-02-01',
    short:'Thousands of community-made games.',
    desc:'Explore thousands of free games created by students and developers on the Scratch platform. From simple platformers to complex RPGs — there\'s something new to discover every visit.',
    tags:['community','educational','kids','variety','creative'],
    instr:'Browse the game library and click any game to play it directly in your browser.',
    ctrl:{keyboard:'Varies by game',mouse:'Varies by game'},
    w:960,h:540,
  }),
  g('g125','Poptropica','poptropica','action','https://poptropica.com',8000000,4.4,32000,{
    dev:'Sandbox Networks',addedAt:'2024-01-15',
    short:'Adventure across islands solving mysteries.',
    desc:'Create your Poptropican and explore dozens of themed islands, each with its own story and puzzles to solve. Collect items, talk to characters, and complete quests in this beloved adventure world.',
    tags:['adventure','islands','kids','story','exploration'],
    instr:'Walk around the island, collect items, and interact with characters to solve each island\'s mystery.',
    ctrl:{keyboard:'Arrow keys to move',mouse:'Click to interact with objects and characters'},
    w:960,h:540,
  }),
  g('g126','Club Penguin Rewritten','club-penguin-rewritten','action','https://cprewritten.net',6000000,4.4,24000,{
    dev:'Community Project',addedAt:'2024-01-20',
    short:'The beloved virtual penguin world, revived.',
    desc:'A community-revived version of the original Club Penguin. Customize your penguin, play mini-games, chat with friends, and explore the island just like in the original.',
    tags:['penguin','social','virtual-world','kids','classic'],
    instr:'Walk around the island, play mini-games in each area, and decorate your igloo.',
    ctrl:{mouse:'Click to walk and interact',keyboard:'Type to chat'},
    w:960,h:540,
  }),
  g('g127','Jackbox Games','jackbox-games','io-games','https://jackboxgames.com',12000000,4.8,48000,{
    dev:'Jackbox Games',featured:true,isHot:true,addedAt:'2024-01-01',
    short:'Party games for groups — phone as controller.',
    desc:'Play hilarious party games with friends using phones as controllers. From Quiplash to Drawful to Trivia Murder Party — Jackbox has the best couch co-op games available online.',
    tags:['party','multiplayer','funny','trivia','drawing'],
    instr:'One player hosts on screen. Everyone else joins on their phone using the room code.',
    ctrl:{mobile:'Players join at jackbox.tv on their phone',keyboard:'Host controls game flow'},
    w:960,h:540,
  }),
  g('g128','EvoWars.io','evowars-io','io-games','https://evowars.io',7000000,4.5,28000,{
    isHot:true,addedAt:'2024-02-05',
    short:'Evolve your warrior through the ages by killing.',
    desc:'Start as a primitive caveman and evolve through history by eliminating other players. Each kill grants XP to evolve into a stronger warrior — from knight to samurai to future soldier.',
    tags:['io','evolution','fighting','multiplayer','warrior'],
    instr:'Attack smaller players to gain XP. Evolve to become stronger. Avoid larger evolved players.',
    ctrl:{mouse:'Move to steer, auto-attacks nearby enemies'},
  }),
  g('g129','Wings.io','wings-io','io-games','https://wings.io',9000000,4.4,36000,{
    isHot:true,addedAt:'2024-02-08',
    short:'Multiplayer plane shooter .io game.',
    desc:'Fly a plane and shoot down other players in this fast-paced aerial .io game. Collect power-up weapons, dodge enemy fire, and become the top ace in a chaotic free-for-all.',
    tags:['planes','io','shooting','multiplayer','aerial'],
    instr:'Fly your plane and shoot enemies. Collect power-ups to get stronger weapons.',
    ctrl:{mouse:'Move to steer plane, auto-fires at enemies'},
  }),
  g('g130','Stabfish.io','stabfish-io','io-games','https://stabfish.io',4000000,4.3,16000,{
    isNew:true,addedAt:'2024-03-08',
    short:'Stab other fish with your spike to grow bigger.',
    desc:'Swim around and stab other fish with your snout to eat them and grow larger. Avoid fish bigger than you and hunt smaller ones in this fast-paced underwater .io game.',
    tags:['io','fish','multiplayer','ocean','survival'],
    instr:'Swim into smaller fish to stab and eat them. Avoid bigger fish that can eat you.',
    ctrl:{mouse:'Move mouse to steer your fish'},
  }),

  // ── EXTRA GAMES: g131-g200 (fill to 200 total) ─────────────────────────

  // Action (g131-g135)
  g('g131','Age of War 2','age-of-war-2','action',cg('age-of-war-2'),7000000,4.5,28000,{
    isHot:true,addedAt:'2024-01-18',
    short:'Evolve your army from cavemen to robots.',
    desc:'Defend your base and attack the enemy through the ages of war. Start with cavemen, evolve to medieval knights, then modern soldiers and futuristic robots. A tower defense meets strategy classic.',
    tags:['strategy','war','evolution','defense','waves'],
    instr:'Spawn units to attack the enemy base. Upgrade your base and evolve to stronger eras.',
    ctrl:{mouse:'Click to spawn units and upgrade'},
  }),
  g('g132','Kingdom Rush','kingdom-rush','action',cg('kingdom-rush'),9000000,4.8,36000,{
    dev:'Ironhide Game Studio',featured:true,isHot:true,addedAt:'2024-01-22',
    short:'The gold standard of tower defense games.',
    desc:'Place towers, upgrade them, and use hero abilities to defend your kingdom from waves of trolls, orcs, and dark wizards. Kingdom Rush is the pinnacle of the tower defense genre.',
    tags:['tower-defense','strategy','kingdom','defense','fantasy'],
    instr:'Place and upgrade towers along enemy paths. Use your hero and abilities to stop waves.',
    ctrl:{mouse:'Click to place, upgrade, and activate abilities'},
  }),
  g('g133','Electric Man 2','electric-man-2','action',cg('electric-man-2'),5500000,4.5,22000,{
    addedAt:'2024-02-12',
    short:'Slow-motion stickman fighting tournament.',
    desc:'Compete in an electrified stickman fighting tournament with stylish slow-motion combat. Punch, kick and throw opponents with perfectly timed moves in this visually striking brawler.',
    tags:['stickman','fighting','slow-motion','tournament','cool'],
    instr:'Use slow motion strategically. Grab and throw enemies into walls for extra damage.',
    ctrl:{keyboard:'WASD to move, J/K/L to punch/kick/grab'},
  }),
  g('g134','Stickman Archer','stickman-archer','action',cg('stickman-archer'),4500000,4.4,18000,{
    addedAt:'2024-02-18',
    short:'One-shot archer duels between stickmen.',
    desc:'Face off against stickman archers in tense one-shot duels. Aim for the kill shot while using trees and terrain for cover. One arrow — one kill. Can you be the last archer standing?',
    tags:['stickman','archery','duels','precision','shooting'],
    instr:'Aim your arrow at the enemy stickman. Release at the right moment for a kill shot.',
    ctrl:{mouse:'Move to aim, click to fire'},
  }),
  g('g135','Super Mario Flash','super-mario-flash','action',cg('super-mario-flash'),7000000,4.6,28000,{
    isHot:true,addedAt:'2024-01-28',
    short:'Fan-made Super Mario in your browser.',
    desc:'A faithful fan recreation of Super Mario Bros in Flash/browser form. Run and jump through classic Mario levels, stomp Goombas, and save the mushroom kingdom.',
    tags:['mario','platformer','classic','nintendo','fan-game'],
    instr:'Run right, jump on enemies, collect coins and mushrooms. Reach the flag to complete each level.',
    ctrl:{keyboard:'Arrow keys to run and jump, Z to run faster'},
  }),

  // Puzzle (g136-g139)
  g('g136','Water Sort Puzzle','water-sort-puzzle','puzzle',cg('water-sort-puzzle'),14000000,4.6,56000,{
    isHot:true,addedAt:'2024-01-25',
    short:'Sort colored water into matching tubes.',
    desc:'Pour colored water between tubes until each tube contains only one color. Sounds simple — the later levels will bend your brain. Relaxing yet deeply satisfying.',
    tags:['sorting','colors','tubes','logic','relaxing'],
    instr:'Tap a tube to select it, then tap another to pour. Sort all colors into single-color tubes.',
    ctrl:{mouse:'Click tube to select, click another tube to pour',touch:'Tap to select and pour'},
  }),
  g('g137','Word Search','word-search-daily','puzzle',cg('word-search'),8000000,4.5,32000,{
    addedAt:'2024-02-05',
    short:'Find hidden words in the letter grid.',
    desc:'Classic word search puzzles with thousands of themes. Find all the hidden words in the grid — they may go forward, backward, up, down, or diagonally. Multiple difficulties.',
    tags:['words','search','grid','letters','casual'],
    instr:'Find all listed words hidden in the letter grid. Click the first and last letter of each word.',
    ctrl:{mouse:'Click and drag to highlight words'},
  }),
  g('g138','Block Puzzle','block-puzzle','puzzle',cg('block-puzzle'),11000000,4.5,44000,{
    isHot:true,addedAt:'2024-01-18',
    short:'Tetris-style block placement with no time pressure.',
    desc:'Place Tetris-style blocks on the board to fill and clear lines and columns. Unlike Tetris, there\'s no time pressure — place blocks thoughtfully to maximize your score.',
    tags:['blocks','tetris','puzzle','relaxing','strategy'],
    instr:'Drag blocks onto the board. Fill complete rows or columns to clear them.',
    ctrl:{mouse:'Click and drag blocks to place them',touch:'Drag to place'},
  }),
  g('g139','Tangram','tangram','puzzle',cg('tangram'),4000000,4.4,16000,{
    addedAt:'2024-02-25',
    short:'Arrange geometric shapes to form silhouettes.',
    desc:'The ancient Chinese puzzle game. Arrange seven geometric pieces to form the given silhouette shape. Hundreds of shapes to solve with no two solutions the same.',
    tags:['tangram','shapes','geometry','classic','brain'],
    instr:'Drag and rotate the seven pieces to fill the outlined shape exactly.',
    ctrl:{mouse:'Click and drag pieces, right-click to rotate'},
  }),

  // Racing (g140-g152)
  g('g140','Moto X3M Spooky Land','moto-x3m-spooky-land','racing',cg('moto-x3m-spooky-land'),6000000,4.7,24000,{
    dev:'Madpuffers',isHot:true,addedAt:'2024-01-08',
    short:'Halloween-themed Moto X3M with spooky levels.',
    desc:'The beloved Moto X3M series goes spooky with Halloween-themed levels full of ghosts, pumpkins and cobwebs. Same great motorbike stunt racing with a seasonal twist.',
    tags:['bike','stunts','racing','halloween','obstacles'],
    instr:'Race through Halloween levels completing stunts. Reach the finish in the fastest time.',
    ctrl:{keyboard:'Up/Down arrows to accelerate/brake, Left/Right to lean'},
  }),
  g('g141','Moto X3M Winter','moto-x3m-winter','racing',cg('moto-x3m-winter'),5500000,4.6,22000,{
    dev:'Madpuffers',isHot:true,addedAt:'2024-01-10',
    short:'Winter-themed motorbike stunt racing.',
    desc:'Moto X3M takes on a winter wonderland with ice ramps, snowmen, and icy terrain. Perform backflips on snowy ramps and navigate freezing obstacles at top speed.',
    tags:['bike','stunts','racing','winter','snow'],
    instr:'Race through winter levels. Land cleanly after ramps for time bonuses.',
    ctrl:{keyboard:'Up/Down arrows to accelerate/brake, Left/Right to lean'},
  }),
  g('g142','Moto X3M Pool Party','moto-x3m-pool-party','racing',cg('moto-x3m-pool-party'),5000000,4.6,20000,{
    dev:'Madpuffers',addedAt:'2024-01-12',
    short:'Pool party-themed Moto X3M levels.',
    desc:'The summer edition of Moto X3M with poolside obstacles, water slides, and beach ramps. Every level is dripping with summer vibes while delivering the same punishing stunt challenge.',
    tags:['bike','stunts','racing','pool','summer'],
    instr:'Navigate pool party obstacles and reach the flag. Do backflips for time bonuses.',
    ctrl:{keyboard:'Up/Down arrows to accelerate/brake, Left/Right to lean'},
  }),
  g('g143','Hill Climbing Race','hill-climbing-race','racing',cg('hill-climbing-race'),10000000,4.5,40000,{
    isHot:true,addedAt:'2024-01-15',
    short:'Drive up hills without running out of fuel.',
    desc:'Drive your vehicle over hilly terrain as far as possible without running out of fuel or flipping over. Collect coins to upgrade your car and unlock new vehicles and tracks.',
    tags:['hill','driving','physics','upgrades','casual'],
    instr:'Accelerate up hills. Collect coins. Don\'t run out of fuel or flip over completely.',
    ctrl:{keyboard:'Right arrow to accelerate, Left arrow to brake'},
  }),
  g('g144','Death Chase','death-chase','racing',cg('death-chase'),3500000,4.3,14000,{
    addedAt:'2024-02-20',
    short:'Motorbike racing with weaponized vehicles.',
    desc:'Race motorbikes on dangerous tracks while avoiding armed enemies trying to destroy you. Weave through traffic, dodge missiles, and outrun your pursuers in this adrenaline racer.',
    tags:['motorbike','combat','racing','weapons','chase'],
    instr:'Ride as fast as possible while avoiding the armed vehicles chasing you.',
    ctrl:{keyboard:'Up arrow to accelerate, Left/Right to steer'},
  }),
  g('g145','Car Eats Car','car-eats-car','racing',cg('car-eats-car'),5000000,4.4,20000,{
    addedAt:'2024-02-10',
    short:'Escape police cars and eat smaller vehicles.',
    desc:'Drive a voracious car that eats smaller vehicles to grow, while escaping the evil police. Collect upgrades and power-ups in this wild vehicular chase game.',
    tags:['car','escape','eating','chase','upgrades'],
    instr:'Drive to escape police. Eat smaller cars to grow. Collect power-ups to survive.',
    ctrl:{keyboard:'Arrow keys or WASD to drive'},
  }),
  g('g146','Extreme Car Driving','extreme-car-driving','racing',cg('extreme-car-driving'),7000000,4.4,28000,{
    isHot:true,addedAt:'2024-01-28',
    short:'Free-roam driving with physics and stunts.',
    desc:'An open-world car driving simulator with realistic physics. Drift, do donuts, pull handbrake turns, and explore the map freely. Great for practicing driving mechanics.',
    tags:['cars','simulator','physics','drifting','free-roam'],
    instr:'Drive freely around the map. Use handbrake for drifts. Explore all areas.',
    ctrl:{keyboard:'WASD to drive, Space for handbrake, C to change camera'},
  }),
  g('g147','Stunt Cars 2','stunt-cars-2','racing',cg('stunt-cars-2'),3000000,4.3,12000,{
    addedAt:'2024-03-01',
    short:'Pull off car stunts on wild obstacle tracks.',
    desc:'Drive specialized stunt cars through extraordinary loop-the-loop and ramp-filled tracks. Time your speed and angle perfectly to land each stunt without crashing.',
    tags:['stunts','cars','loops','racing','physics'],
    instr:'Hit ramps at the right speed. Complete loops and land cleanly to advance.',
    ctrl:{keyboard:'Arrow keys to accelerate, brake, and lean'},
  }),
  g('g148','Motocross Nitro','motocross-nitro','racing',cg('motocross-nitro'),4000000,4.4,16000,{
    addedAt:'2024-02-08',
    short:'Motocross racing with nitro boosts and tricks.',
    desc:'Race motocross bikes on outdoor tracks, use nitro boosts on straightaways, and earn trick points by pulling off flips on ramps. A polished motocross experience in the browser.',
    tags:['motocross','bike','racing','tricks','nitro'],
    instr:'Race to the finish using nitro on straights. Pull tricks off ramps for bonus points.',
    ctrl:{keyboard:'Arrow keys to drive, Nitro auto-charges'},
  }),
  g('g149','Super Bikes 2','super-bikes-2','racing',cg('super-bikes-2'),3500000,4.3,14000,{
    addedAt:'2024-02-15',
    short:'High-speed superbike racing on real tracks.',
    desc:'Race sleek superbikes on real-world inspired circuits. Lean into corners, find the racing line, and blast down straights. Multiple bikes and tracks to unlock.',
    tags:['superbike','racing','motorcycle','tracks','speed'],
    instr:'Lean into corners at the right moment. Find the optimal racing line for each track.',
    ctrl:{keyboard:'Up arrow to accelerate, Down to brake, Left/Right to lean'},
  }),
  g('g150','Mad Truckers','mad-truckers','racing',cg('mad-truckers'),3000000,4.2,12000,{
    addedAt:'2024-03-05',
    short:'Truck racing with weapons and mayhem.',
    desc:'Race massive trucks on outlaw tracks while using weapons to blow up rival truckers. Collect power-ups, upgrade your rig, and dominate the outlaw trucking circuit.',
    tags:['trucks','racing','weapons','combat','outlaw'],
    instr:'Race to first place using weapons on rival trucks. Collect coins for upgrades.',
    ctrl:{keyboard:'Arrow keys to drive, Space to shoot'},
  }),
  g('g151','Offroad Racers','offroad-racers','racing',cg('offroad-racers'),2800000,4.2,11000,{
    addedAt:'2024-03-08',
    short:'Multiplayer offroad racing on dirt tracks.',
    desc:'Race off-road vehicles on muddy, bumpy tracks against other players. Upgrade your 4x4 and master the rough terrain to win championships.',
    tags:['offroad','4x4','racing','multiplayer','dirt'],
    instr:'Navigate rough terrain to reach the finish first. Upgrade your vehicle between races.',
    ctrl:{keyboard:'Arrow keys or WASD to drive'},
  }),
  g('g152','City Car Stunt 4','city-car-stunt-4','racing',cg('city-car-stunt-4'),3200000,4.3,13000,{
    isNew:true,addedAt:'2024-03-12',
    short:'City-based car stunt challenges.',
    desc:'Complete hair-raising stunt challenges in a city environment. Drive through loops, fly over ramps between skyscrapers, and land perfectly on floating platforms.',
    tags:['stunts','city','cars','loops','challenges'],
    instr:'Complete each stunt challenge. Reach the finish marker to advance to the next stunt.',
    ctrl:{keyboard:'WASD to drive, Space for handbrake'},
  }),

  // Shooting (g153-g164)
  g('g153','Pixel Gun Apocalypse 3','pixel-gun-apocalypse-3','shooting',cg('pixel-gun-apocalypse-3'),5000000,4.4,20000,{
    isHot:true,addedAt:'2024-01-20',
    short:'Pixelated multiplayer FPS with many weapons.',
    desc:'Fast-paced pixel-art multiplayer shooter with tons of weapons. Battle on blocky maps in team deathmatch and free-for-all modes. Simple controls, deep weapon variety.',
    tags:['fps','pixel','multiplayer','shooting','weapons'],
    instr:'Join a match and eliminate enemies. Switch weapons to find your favorite.',
    ctrl:{keyboard:'WASD to move, R reload',mouse:'Aim and left-click to shoot'},
  }),
  g('g154','Combat Online','combat-online','shooting',cg('combat-online'),6000000,4.4,24000,{
    isHot:true,addedAt:'2024-01-25',
    short:'Multiplayer team-based combat shooter.',
    desc:'Team-based multiplayer combat with multiple maps and game modes. Work with teammates to eliminate the opposing team. Unlock new weapons and rise through the ranks.',
    tags:['fps','multiplayer','team','combat','online'],
    instr:'Work with your team to eliminate enemies. Protect your base and capture objectives.',
    ctrl:{keyboard:'WASD to move, R reload',mouse:'Aim and left-click to shoot'},
  }),
  g('g155','Sniper Assassin','sniper-assassin','shooting',cg('sniper-assassin'),4500000,4.4,18000,{
    addedAt:'2024-02-05',
    short:'Stealthy sniper missions — eliminate targets.',
    desc:'Complete covert sniper missions by eliminating specific targets without alerting others. Read the mission briefing, identify your target, and take the shot at the perfect moment.',
    tags:['sniper','stealth','missions','precision','shooting'],
    instr:'Read mission objectives. Identify the target. Time your shot when no one is watching.',
    ctrl:{mouse:'Aim and click to fire sniper rifle',keyboard:'Zoom controls'},
  }),
  g('g156','Stick War','stick-war','shooting',cg('stick-war'),7000000,4.6,28000,{
    dev:'Jason Whitham',isHot:true,addedAt:'2024-01-12',
    short:'Command stickman armies in strategic battles.',
    desc:'Control an army of stickmen as they battle for territory. Manually control individual units or manage the army from above. Conquer enemy nations by destroying their statues.',
    tags:['strategy','stickman','war','army','rts'],
    instr:'Train units and control them manually or in formation. Destroy the enemy statue to win.',
    ctrl:{keyboard:'Number keys to spawn units, space to toggle control mode',mouse:'Click to control selected unit'},
  }),
  g('g157','Mad Guns','mad-guns','shooting',cg('mad-guns'),3500000,4.3,14000,{
    addedAt:'2024-02-20',
    short:'Top-down shooter with tons of weapons.',
    desc:'A bird\'s-eye view shooter where you fight through waves of enemies with an arsenal of weapons. Loot better guns from fallen enemies and survive increasingly deadly waves.',
    tags:['topdown','shooter','weapons','waves','loot'],
    instr:'Move and shoot enemies. Loot dropped weapons to upgrade your arsenal.',
    ctrl:{keyboard:'WASD to move',mouse:'Aim and left-click to shoot'},
  }),
  g('g158','SWAT and Zombies','swat-and-zombies','shooting',cg('swat-and-zombies'),4000000,4.4,16000,{
    addedAt:'2024-02-15',
    short:'Defend against zombie waves as a SWAT team.',
    desc:'Command a SWAT team defending against relentless zombie hordes. Deploy officers, set up barricades, and use special weapons to survive increasingly massive waves.',
    tags:['swat','zombies','defense','shooting','strategy'],
    instr:'Place SWAT officers and set up defenses. Survive all zombie waves to advance.',
    ctrl:{mouse:'Click to place units and activate abilities'},
  }),
  g('g159','Gun Mayhem 2','gun-mayhem-2','shooting',cg('gun-mayhem-2'),5500000,4.5,22000,{
    isHot:true,addedAt:'2024-01-30',
    short:'Platform shooter — knock opponents off the stage.',
    desc:'An arena platform shooter where the goal is to blast opponents off the stage with an ever-changing arsenal. Grab weapon crates, use power-ups, and be the last one standing.',
    tags:['platform','shooter','arena','weapons','local'],
    instr:'Shoot opponents to push them off the stage. Grab weapon crates for new guns.',
    ctrl:{keyboard:'WASD to move/jump, F to shoot'},
  }),
  g('g160','War Brokers','war-brokers','shooting','https://warbrokers.io',5000000,4.5,20000,{
    isHot:true,addedAt:'2024-02-02',
    short:'Browser FPS with vehicles and team battles.',
    desc:'A multiplayer FPS with vehicles — drive tanks, fly helicopters, and fight on foot. Battle in team modes across detailed maps with objectives. One of the best browser FPS games.',
    tags:['fps','multiplayer','vehicles','team','3d'],
    instr:'Fight on foot or commandeer vehicles. Complete team objectives to win rounds.',
    ctrl:{keyboard:'WASD to move, R reload',mouse:'Aim and left-click to shoot'},
  }),
  g('g161','Stickman Sniper 3','stickman-sniper-3','shooting',cg('stickman-sniper-3'),3200000,4.3,13000,{
    addedAt:'2024-02-25',
    short:'Snipe stickmen from long distance.',
    desc:'Pick off stickman targets with your sniper rifle from long range. Each level gives you limited bullets to eliminate all targets without hitting innocent bystanders.',
    tags:['sniper','stickman','precision','puzzle','shooting'],
    instr:'Use limited bullets to eliminate all marked stickman targets. Avoid innocents.',
    ctrl:{mouse:'Aim and click to fire'},
  }),
  g('g162','Commando Rush','commando-rush','shooting',cg('commando-rush'),2800000,4.2,11000,{
    addedAt:'2024-03-10',
    short:'Side-scrolling soldier shooter.',
    desc:'Run through enemy-filled levels as a commando, blasting soldiers and dodging bullets. Collect weapon upgrades and survive boss encounters in this classic side-scrolling shooter.',
    tags:['commando','sidescroller','soldiers','shooting','action'],
    instr:'Move right and shoot enemies. Duck under bullets and collect power-ups.',
    ctrl:{keyboard:'Arrow keys to move, Z to shoot, X for grenades'},
  }),
  g('g163','Sniper 3D','sniper-3d','shooting',cg('sniper-3d'),8000000,4.5,32000,{
    isHot:true,addedAt:'2024-01-22',
    short:'Realistic 3D sniper missions in urban settings.',
    desc:'Complete precision sniper missions across urban environments. Eliminate specific targets from long range with realistic ballistics. Upgrade your rifles between missions.',
    tags:['sniper','3d','realistic','missions','shooting'],
    instr:'Complete mission objectives using your sniper rifle. Aim carefully for headshots.',
    ctrl:{mouse:'Aim and right-click to zoom, left-click to fire'},
  }),
  g('g164','Zombies vs Penguins','zombies-vs-penguins','shooting',cg('zombies-vs-penguins'),2500000,4.2,10000,{
    addedAt:'2024-03-15',
    short:'Penguins battle the zombie apocalypse.',
    desc:'Control penguins armed with weapons fighting off zombie hordes. Wacky, colorful, and surprisingly tactical — upgrade your penguin squad and survive the zombie onslaught.',
    tags:['zombies','penguins','shooting','funny','waves'],
    instr:'Aim and shoot zombies approaching your position. Upgrade weapons between waves.',
    ctrl:{mouse:'Aim and left-click to shoot'},
  }),

  // Sports (g165-g175)
  g('g165','Mini Golf Club','mini-golf-club','sports',cg('mini-golf-club'),7000000,4.6,28000,{
    isHot:true,addedAt:'2024-01-18',
    short:'Relaxing mini golf with creative courses.',
    desc:'Play mini golf on beautifully crafted courses with windmills, water hazards, and trick shots. Compete online or work through the solo campaign to unlock harder courses.',
    tags:['golf','mini','putting','casual','relaxing'],
    instr:'Aim and click to set power. Get the ball in the hole with as few strokes as possible.',
    ctrl:{mouse:'Click and drag to aim, release to set power'},
  }),
  g('g166','Bowling Crew','bowling-crew','sports',cg('bowling-crew'),6000000,4.5,24000,{
    isHot:true,addedAt:'2024-01-22',
    short:'Multiplayer bowling with spin mechanics.',
    desc:'Bowl against real players in this realistic online bowling game. Apply spin, aim for the pocket, and pick up difficult spares. Multiple ball types and a deep progression system.',
    tags:['bowling','pins','spin','multiplayer','realistic'],
    instr:'Swipe to aim and apply spin. Hit the pocket for strikes and clean up spares.',
    ctrl:{mouse:'Click drag and swipe to throw the ball with spin'},
  }),
  g('g167','Penalty Kick Online','penalty-kick-online','sports',cg('penalty-kick-online'),8000000,4.5,32000,{
    dev:'RHM Interactive',isHot:true,addedAt:'2024-01-10',
    short:'Real-time multiplayer penalty shootout.',
    desc:'Go head to head in real-time penalty shootouts. One player shoots while the other dives as goalkeeper. Best of 5 penalties — the tension is real in this multiplayer soccer duel.',
    tags:['soccer','penalties','multiplayer','goalkeeper','football'],
    instr:'Aim your shot and choose power as the kicker. Time your dive as the goalkeeper.',
    ctrl:{mouse:'Click to aim and shoot or dive'},
  }),
  g('g168','Badminton Blitz','badminton-blitz','sports',cg('badminton-blitz'),3000000,4.3,12000,{
    addedAt:'2024-02-20',
    short:'Fast-paced badminton with skill shots.',
    desc:'Rally birdies in fast-paced badminton matches. Time your smashes and drops perfectly. Defeat AI opponents of increasing difficulty to become the world badminton champion.',
    tags:['badminton','racket','smash','sports','casual'],
    instr:'Hit the shuttlecock back over the net. Use smashes when the birdie is high.',
    ctrl:{keyboard:'Arrow keys to move, Z to hit normally, X to smash'},
  }),
  g('g169','Soccer Physics','soccer-physics','sports',cg('soccer-physics'),5000000,4.4,20000,{
    dev:'RHM Interactive',isHot:true,addedAt:'2024-02-05',
    short:'Wacky one-button soccer with physics chaos.',
    desc:'The most unpredictable soccer game ever. One button controls your entire team with bizarre ragdoll physics. Every match descends into hilarious chaos. Great fun with two players.',
    tags:['soccer','physics','funny','casual','2player'],
    instr:'Press your button to jump and kick. Score more goals than the opponent.',
    ctrl:{keyboard:'Player 1: W | Player 2: Up Arrow'},
  }),
  g('g170','Real Football','real-football','sports',cg('real-football'),5500000,4.4,22000,{
    addedAt:'2024-01-28',
    short:'Realistic browser football management game.',
    desc:'Manage your football club, sign players, train your squad, and compete in leagues and cups. Full management depth in a browser game — from tactics to transfer budgets.',
    tags:['football','management','soccer','team','simulation'],
    instr:'Manage transfers, training, and tactics. Win matches by setting up the right formation.',
    ctrl:{mouse:'Click menus to manage your team',keyboard:'Varies during matches'},
  }),
  g('g171','Ice Hockey','ice-hockey','sports',cg('ice-hockey'),3500000,4.3,14000,{
    addedAt:'2024-02-12',
    short:'Browser ice hockey with quick matches.',
    desc:'Play fast and furious ice hockey matches in the browser. Control your players, pass, shoot, and score. Simple controls with just enough depth for exciting close games.',
    tags:['hockey','ice','sports','puck','casual'],
    instr:'Move your players to the puck. Pass and shoot to score goals.',
    ctrl:{keyboard:'Arrow keys to move, Z to shoot/pass',mouse:'Click to shoot'},
  }),
  g('g172','Baseball Pro','baseball-pro','sports',cg('baseball-pro'),3000000,4.2,12000,{
    addedAt:'2024-02-28',
    short:'Browser baseball with pitching and batting.',
    desc:'Step up to the plate or take the mound in this browser baseball game. Time your swing perfectly as a batter or vary your pitches to strike batters out as a pitcher.',
    tags:['baseball','batting','pitching','sports','casual'],
    instr:'As batter: swing at the right moment. As pitcher: choose pitch type and location.',
    ctrl:{keyboard:'Space to swing/pitch',mouse:'Click to aim pitch or swing'},
  }),
  g('g173','Darts','darts','sports',cg('darts'),4500000,4.5,18000,{
    addedAt:'2024-02-08',
    short:'Classic darts — hit 301 first to win.',
    desc:'Play classic 301 or 501 darts against the computer or a friend. Aim for the bullseye, score doubles and triples, and check out perfectly to win the leg.',
    tags:['darts','precision','aiming','classic','sports'],
    instr:'Click and release at the right moment to throw your dart. Aim for high scores and checkouts.',
    ctrl:{mouse:'Move to aim, click to throw'},
  }),
  g('g174','Tennis Stars','tennis-stars','sports',cg('tennis-stars'),4000000,4.4,16000,{
    addedAt:'2024-02-22',
    short:'Top-down tennis with topspin and slice.',
    desc:'Play tennis from a top-down perspective with full topspin, flat, and slice shot mechanics. Compete in grand slam tournaments and defeat increasingly skilled opponents.',
    tags:['tennis','racket','sports','tournament','multiplayer'],
    instr:'Move to the ball and hit with the appropriate shot type. Win games, sets, and the match.',
    ctrl:{keyboard:'WASD to move, Z/X/C for shot types'},
  }),
  g('g175','Golf Orbit','golf-orbit','sports',cg('golf-orbit'),3500000,4.3,14000,{
    isNew:true,addedAt:'2024-03-18',
    short:'Launch golf balls into orbit for max distance.',
    desc:'Hit a golf ball as far as possible — through the atmosphere, into space, and beyond. Upgrade your clubs, balls, and spacesuits to achieve impossible distances.',
    tags:['golf','launch','idle','upgrades','distance'],
    instr:'Click to swing. Use upgrades to go further each shot.',
    ctrl:{mouse:'Click to swing at the right moment'},
  }),

  // IO Games (g176-g180)
  g('g176','Gats.io','gats-io','io-games','https://gats.io',6000000,4.5,24000,{
    isHot:true,addedAt:'2024-01-18',
    short:'Top-down multiplayer shooter with builds.',
    desc:'A top-down arena shooter where you eliminate others to climb the leaderboard. Build walls for cover, choose from multiple weapon classes, and dominate the arena.',
    tags:['io','shooter','topdown','multiplayer','building'],
    instr:'Move and shoot other players. Build walls for cover. Collect XP to evolve.',
    ctrl:{keyboard:'WASD to move',mouse:'Aim and left-click to shoot, right-click to build'},
  }),
  g('g177','Blob.io','blob-io','io-games','https://blob.io',4500000,4.3,18000,{
    addedAt:'2024-02-12',
    short:'Eat smaller blobs and grow bigger.',
    desc:'Control a blob and eat smaller blobs to grow. Split yourself to move faster or capture prey. Avoid larger blobs that will eat you in this relaxing take on the .io formula.',
    tags:['io','blob','eating','multiplayer','grow'],
    instr:'Eat food and smaller blobs to grow. Split to move faster. Avoid blobs larger than you.',
    ctrl:{mouse:'Move mouse to control blob direction'},
  }),
  g('g178','Spinz.io','spinz-io','io-games','https://spinz.io',4000000,4.2,16000,{
    addedAt:'2024-02-20',
    short:'Spin fidget spinners and eliminate others.',
    desc:'Spin up your fidget spinner and knock out other players with your rotating blade. The faster your spin, the more damage you deal. Collect energy to keep spinning.',
    tags:['io','spinner','fidget','multiplayer','spin'],
    instr:'Move your spinner around and slam into others. Keep collecting orbs to stay fast.',
    ctrl:{mouse:'Move mouse to control spinner position'},
  }),
  g('g179','Bonk.io','bonk-io','io-games','https://bonk.io',7000000,4.6,28000,{
    dev:'Chaz',isHot:true,addedAt:'2024-01-25',
    short:'Physics ball multiplayer — knock others off.',
    desc:'Push opponents off custom physics maps in this multiplayer ball game. Create your own maps, play ranked matches, and master the momentum-based controls to become the top bonker.',
    tags:['io','physics','ball','multiplayer','custom-maps'],
    instr:'Move and slam your ball into others to push them off the edge.',
    ctrl:{keyboard:'WASD to move, X to slow down (heavy mode)'},
  }),
  g('g180','Superhex.io','superhex-io','io-games','https://superhex.io',3500000,4.2,14000,{
    addedAt:'2024-03-05',
    short:'Expand hexagonal territory in this .io game.',
    desc:'Start with a small hexagon base and expand your territory by claiming neighboring hexagons. Cut off opponents to eat their territory in this chill but competitive strategy game.',
    tags:['io','hexagon','territory','strategy','multiplayer'],
    instr:'Move to capture adjacent hexagons. Cut others off to claim their territory.',
    ctrl:{mouse:'Move cursor to control your hexagon'},
  }),

  // Hypercasual (g181-g190)
  g('g181','Hole.io','hole-io','hypercasual',cg('hole-io'),12000000,4.6,48000,{
    isHot:true,addedAt:'2024-01-18',
    short:'Control a black hole and swallow the city.',
    desc:'Control a growing black hole and swallow increasingly large objects — benches, cars, buildings, entire city blocks. Compete with other holes in a timed city-eating frenzy.',
    tags:['hole','eating','city','casual','growing'],
    instr:'Move your hole to swallow objects. Grow large enough to eat bigger and bigger items.',
    ctrl:{mouse:'Click and drag to move the hole',touch:'Drag to control'},
  }),
  g('g182','Color Switch','color-switch','hypercasual',cg('color-switch'),9000000,4.4,36000,{
    isHot:true,addedAt:'2024-01-22',
    short:'Tap to pass through matching color segments.',
    desc:'Guide a bouncing ball through rotating obstacles by only passing through the matching color. One wrong color and you start over. Simple mechanics, brutal difficulty after level 10.',
    tags:['colors','ball','matching','casual','hard'],
    instr:'Tap to bounce the ball upward. Pass through the part of the obstacle matching your ball color.',
    ctrl:{mouse:'Click to bounce',touch:'Tap to bounce'},
    w:480,h:640,
  }),
  g('g183','Crossy Road','crossy-road','hypercasual',cg('crossy-road'),14000000,4.6,56000,{
    isHot:true,addedAt:'2024-01-08',
    short:'Hop across roads, rivers, and trains endlessly.',
    desc:'Help your chicken (and hundreds of other characters) hop across an endless series of roads, rivers, and train tracks without getting squashed. A modern take on the Frogger formula.',
    tags:['hopping','crossing','endless','chicken','casual'],
    instr:'Tap to hop forward, left, or right. Cross roads and rivers without getting hit.',
    ctrl:{keyboard:'Arrow keys to hop',touch:'Tap directionally'},
  }),
  g('g184','Tunnel Rush','tunnel-rush','hypercasual',cg('tunnel-rush'),10000000,4.5,40000,{
    isHot:true,addedAt:'2024-01-20',
    short:'Speed through a neon tunnel dodging obstacles.',
    desc:'Race through a neon-lit 3D tunnel at breakneck speed, dodging obstacles that appear without warning. The speed continuously increases. How long can you survive?',
    tags:['tunnel','speed','neon','endless','reflex'],
    instr:'Move left and right to dodge obstacles. Don\'t hit anything or it\'s game over.',
    ctrl:{keyboard:'Left/Right arrows or A/D to dodge',touch:'Tilt or tap'},
  }),
  g('g185','Going Balls','going-balls','hypercasual',cg('going-balls'),8000000,4.4,32000,{
    isHot:true,addedAt:'2024-02-01',
    short:'Roll a ball along a floating track.',
    desc:'Guide a ball along a narrow floating track in the sky. One wrong move sends you tumbling into the void. Simple controls but nail-biting precision required on each elevated course.',
    tags:['ball','balance','track','casual','precision'],
    instr:'Swipe left/right to steer the ball. Keep it on the track as long as possible.',
    ctrl:{keyboard:'Left/Right arrows',touch:'Swipe left/right'},
    w:480,h:640,
  }),
  g('g186','Stack Jump','stack-jump','hypercasual',cg('stack-jump'),6000000,4.3,24000,{
    isNew:true,addedAt:'2024-03-15',
    short:'Jump through platforms and stack up high.',
    desc:'Bounce a ball upward through stacked platforms, breaking through colored segments and collecting points. A satisfying hypercasual game where height is the only goal.',
    tags:['stacking','jumping','ball','casual','colorful'],
    instr:'Tap to bounce the ball. Break through platforms to rise higher.',
    ctrl:{mouse:'Click to bounce',touch:'Tap to bounce'},
    w:480,h:640,
  }),
  g('g187','Piano Tiles 2','piano-tiles-2','hypercasual',cg('piano-tiles-2'),15000000,4.6,60000,{
    isHot:true,addedAt:'2024-01-12',
    short:'Tap black tiles to play beautiful piano music.',
    desc:'Tap the falling black tiles in time to play famous piano pieces. Don\'t miss a tile or tap a white one. Increasingly fast tempos and longer songs test your reflexes.',
    tags:['piano','music','tiles','tapping','rhythm'],
    instr:'Tap only the black tiles as they fall. Miss one or tap white and you lose.',
    ctrl:{mouse:'Click black tiles as they fall',touch:'Tap black tiles'},
  }),
  g('g188','Idle Farming Business','idle-farming-business','hypercasual',cg('idle-farming-business'),5000000,4.4,20000,{
    addedAt:'2024-02-10',
    short:'Build a farm empire from a single crop.',
    desc:'Plant crops, harvest them, and reinvest profits into bigger and better farm equipment. An idle farming game where your empire grows even when you\'re not actively playing.',
    tags:['idle','farming','business','crops','casual'],
    instr:'Plant and harvest crops. Use earnings to buy better equipment and expand your farm.',
    ctrl:{mouse:'Click to plant, harvest, and purchase upgrades'},
  }),
  g('g189','Paper Fold','paper-fold','hypercasual',cg('paper-fold'),7000000,4.5,28000,{
    isHot:true,addedAt:'2024-02-18',
    short:'Fold paper to match the target image.',
    desc:'Fold a piece of paper by clicking on fold lines to reveal a hidden image. Match the target silhouette by folding in the right sequence. Meditative and surprisingly satisfying.',
    tags:['paper','folding','origami','casual','puzzle'],
    instr:'Click fold lines to fold the paper. Match the target image shown.',
    ctrl:{mouse:'Click fold lines to fold'},
  }),
  g('g190','Jumping Ball Adventure','jumping-ball-adventure','hypercasual',cg('jumping-ball-adventure'),4000000,4.2,16000,{
    isNew:true,addedAt:'2024-03-20',
    short:'Jump a ball through colorful obstacle worlds.',
    desc:'Guide a bouncy ball through vibrant platformer levels filled with spikes, gaps, and spinning obstacles. Time jumps precisely to collect stars and reach the end of each world.',
    tags:['ball','jumping','platformer','casual','colorful'],
    instr:'Tap or click to jump. Avoid spikes and obstacles. Collect stars for bonus points.',
    ctrl:{mouse:'Click to jump',touch:'Tap to jump',keyboard:'Space to jump'},
    w:480,h:640,
  }),

  // 2-Player (g191-g200)
  g('g191','Fireboy Watergirl Crystal Temple','fireboy-and-watergirl-crystal-temple','2-player',cg('fireboy-and-watergirl-the-crystal-temple'),9000000,4.7,36000,{
    dev:'Oslo Albet',isHot:true,addedAt:'2024-01-09',
    short:'Co-op puzzles in the Crystal Temple.',
    desc:'The fourth entry in the beloved series ventures into the Crystal Temple. New crystal mechanics and mirrored puzzle rooms add fresh challenges. Coordinate precisely with your partner.',
    tags:['2player','coop','puzzle','platformer','crystal'],
    instr:'Guide both characters to their exits. Use crystal mirrors to redirect and solve puzzles.',
    ctrl:{keyboard:'Fireboy: Arrow Keys | Watergirl: WAD'},
  }),
  g('g192','Bad Ice Cream','bad-ice-cream','2-player',cg('bad-ice-cream'),6000000,4.5,24000,{
    dev:'Nitrome',isHot:true,addedAt:'2024-01-14',
    short:'Co-op ice cream character adventure.',
    desc:'Play as ice cream characters collecting fruits while freezing enemies. Work with a partner to clear each level efficiently, using your freeze ability to create paths and trap enemies.',
    tags:['2player','coop','puzzle','ice-cream','nitrome'],
    instr:'Collect all the fruit in each level. Freeze enemies and create ice block paths.',
    ctrl:{keyboard:'Player 1: WASD + space to freeze | Player 2: Arrow keys + shift to freeze'},
  }),
  g('g193','Wrestle Brothers','wrestle-brothers','2-player',cg('wrestle-brothers'),3500000,4.4,14000,{
    addedAt:'2024-02-15',
    short:'2-player wrestling with grapples and slams.',
    desc:'Grab, throw, and slam your opponent in this chaotic wrestling game for two players. Execute different wrestling moves by combining directional inputs with the action button.',
    tags:['wrestling','2player','local','physics','funny'],
    instr:'Grab your opponent and throw them into the mat. Use directional inputs for different moves.',
    ctrl:{keyboard:'Player 1: WASD + E | Player 2: Arrow keys + I'},
  }),
  g('g194','Cup Pong','cup-pong','2-player',cg('cup-pong'),4000000,4.4,16000,{
    isHot:true,addedAt:'2024-02-08',
    short:'Multiplayer beer pong in your browser.',
    desc:'Play beer pong against a friend or computer. Aim your throw and sink the ball into the opponent\'s cups. Bounce shots and special throws add depth to this simple but fun party game.',
    tags:['2player','pong','cups','party','aim'],
    instr:'Aim and adjust power to throw the ball into opponent\'s cups. Sink all cups to win.',
    ctrl:{mouse:'Click and drag to aim, release to throw'},
  }),
  g('g195','Double Head Soccer','double-head-soccer','2-player',cg('double-head-soccer'),5000000,4.4,20000,{
    dev:'Headz Games',isHot:true,addedAt:'2024-01-28',
    short:'Hilarious big-headed soccer for 2 players.',
    desc:'Two giant-headed players face off on a tiny soccer pitch. Jump, headbutt, and kick the ball into the goal using your enormous head. Chaotic, hilarious and perfect for quick matches.',
    tags:['soccer','2player','funny','heads','local'],
    instr:'Jump and use your big head to hit the ball into the opponent\'s goal.',
    ctrl:{keyboard:'Player 1: W to jump, A/D to move | Player 2: Arrow keys'},
  }),
  g('g196','Tank Trouble','tank-trouble','2-player',cg('tank-trouble'),8000000,4.5,32000,{
    dev:'Mads Purup',isHot:true,addedAt:'2024-01-05',
    short:'Bouncy bullet tank battles for 2-3 players.',
    desc:'Battle in a maze where bullets bounce off walls. Shoot your opponents before they shoot you — the ricocheting bullets can come back to destroy you. Classic browser multiplayer.',
    tags:['tanks','2player','maze','bullets','classic'],
    instr:'Navigate the maze and shoot opponents. Watch out for your own ricocheting bullets.',
    ctrl:{keyboard:'Player 1: ESDF + Q to shoot | Player 2: Arrow keys + M to shoot'},
  }),
  g('g197','Bomb It','bomb-it','2-player',cg('bomb-it'),6500000,4.5,26000,{
    dev:'Agame',isHot:true,addedAt:'2024-01-10',
    short:'Bomberman-style 2-player arena game.',
    desc:'A Bomberman-inspired 2-player arena game. Place bombs to blow up walls and eliminate your opponent. Collect power-ups to get bigger bombs and blast through more blocks.',
    tags:['bomberman','2player','bombs','arena','classic'],
    instr:'Place bombs strategically to blast your opponent. Collect power-ups to upgrade your bombs.',
    ctrl:{keyboard:'Player 1: WASD + space | Player 2: Arrow keys + shift'},
  }),
  g('g198','Dual','dual','2-player',cg('dual'),3000000,4.3,12000,{
    addedAt:'2024-02-22',
    short:'2-player shooter — point phones at each other.',
    desc:'A unique 2-player game designed for two devices. Point your screens at each other and shoot the spaceship that appears on the other screen. The most creative local multiplayer setup.',
    tags:['2player','unique','shooting','mobile','creative'],
    instr:'Hold your device facing the other player\'s device. Tap to shoot at their spaceship.',
    ctrl:{touch:'Tap your screen to shoot',keyboard:'Space to shoot'},
  }),
  g('g199','Ping Pong Pro','ping-pong-pro','2-player',cg('ping-pong-pro'),4500000,4.4,18000,{
    addedAt:'2024-02-05',
    short:'Fast-paced 2-player ping pong.',
    desc:'Compete against a friend or AI in this lightning-fast ping pong game. Add topspin, backspin, and precision placement to outplay your opponent. First to 11 wins the set.',
    tags:['pingpong','2player','sports','table-tennis','fast'],
    instr:'Move your paddle to return shots. Apply spin by moving while hitting.',
    ctrl:{keyboard:'Player 1: W/S | Player 2: Up/Down arrows'},
  }),
  g('g200','Stickman Wrestling','stickman-wrestling','2-player',cg('stickman-wrestling'),3500000,4.3,14000,{
    isNew:true,addedAt:'2024-03-25',
    short:'Silly stickman wrestling match for two.',
    desc:'Two stickmen wrestle in an over-the-top brawl. Grapple, throw, and pin your opponent with simple but expressive controls. Ragdoll physics make every match uniquely hilarious.',
    tags:['stickman','wrestling','2player','ragdoll','funny'],
    instr:'Grab and throw your opponent. Pin them to the mat to score.',
    ctrl:{keyboard:'Player 1: WASD + E | Player 2: Arrow keys + O'},
  }),
];

// Filter duplicates
const toAdd = newGames.filter(g => !existingSlugs.has(g.slug) && !blocked.has(g.slug));
const skipped = newGames.filter(g => existingSlugs.has(g.slug) || blocked.has(g.slug));
if (skipped.length > 0) {
  console.log(`Skipped ${skipped.length} duplicates: ${skipped.map(g=>g.slug).join(', ')}`);
}

const merged = [...existing, ...toAdd];
writeFileSync(gamesPath, JSON.stringify(merged, null, 2));

// Update category counts
const counts = {};
for (const game of merged) {
  counts[game.category] = (counts[game.category] || 0) + 1;
}
const categories = JSON.parse(readFileSync(categoriesPath, 'utf8'));
for (const cat of categories) {
  if (counts[cat.slug] !== undefined) cat.gameCount = counts[cat.slug];
}
writeFileSync(categoriesPath, JSON.stringify(categories, null, 2));

console.log(`\nTotal games: ${merged.length}`);
Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([k,v]) => console.log(`  ${k}: ${v}`));
